### PR TITLE
Make it compatible with Rails 3.1

### PR DESCRIPTION
**Pull request by jodosha**
There is still one missing error in the specs.

### CODE REVIEW

**Comment by jspooner** [comment]
+1

**Comment by dukex** [comment]
+1

**Comment by partydrone** [comment]
+1

**Comment by raw1z** [comment]
+1

**Comment by zapnap** [comment]
+1 is this project still alive?

**Comment by coryschires** [comment]
+1

**Comment by ali** [comment]
How do I get my app to use this version of the gem rather than the "latest" version?

**Comment by jodosha** [comment]
@ali:

```
# Gemfile
gem 'vestal_versions', :git => 'git://github.com/jodosha/vestal_versions.git'
```

**Comment by petecocoon** [comment]
+1

**Comment by dreamr** [comment]
This is a duplicate, and the code (and more for rails 3.2) is now on master. Thanks!

**Pull request closed without merging**
